# Generated by Django 4.1.2 on 2023-01-04 09:19

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile Photo', null=True, upload_to=account.models.profile_photo_upload),
        ),
    ]
