# Generated by Django 4.1.2 on 2022-11-23 14:58

from django.db import migrations
import django.contrib.postgres.search


class Migration(migrations.Migration):

    dependencies = [
        ('USCODE', '0001_initial'),
    ]

    operations = [

        # add field postgres GIN indexed vector_column to table uscode_node
        migrations.AddField(
            model_name='Node',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),

        # add trigger to table uscode_node for
        # field vector_column, content and title
        migrations.RunSQL(

            sql="""
                CREATE TRIGGER usc_uscode_vector_update
                BEFORE INSERT OR UPDATE
                ON uscode_node
                FOR EACH ROW EXECUTE PROCEDURE
                tsvector_update_trigger(
                    vector_column, 'pg_catalog.english', content, title
                );
            """,
            reverse_sql="""
                DROP TRIGGER usc_uscode_vector_update ON uscode_node;
            """,
        ),

    ]
