# Generated by Django 4.1.2 on 2022-11-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFRNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(editable=False, max_length=1024, unique=True)),
                ('up_to_date_as_of', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=225)),
                ('label', models.CharField(max_length=1024)),
                ('label_level', models.CharField(max_length=255)),
                ('label_description', models.CharField(max_length=1024)),
                ('reserved', models.BooleanField(default=False)),
                ('volumes', models.CharField(blank=True, max_length=10, null=True)),
                ('descendant_range_start', models.CharField(max_length=10, null=True)),
                ('descendant_range_end', models.CharField(max_length=10, null=True)),
                ('node_type', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CFR.cfrnode')),
                ('title_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_nodes', to='CFR.cfrnode')),
            ],
            options={
                'verbose_name': 'CFR Node',
                'verbose_name_plural': 'CFR Nodes',
                'db_table': 'cfr_node',
            },
        ),
    ]
