# Generated by Django 4.1.2 on 2022-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfrnode',
            name='descendant_range_end',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cfrnode',
            name='descendant_range_start',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cfrnode',
            name='volumes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
